Repository axinc-ai/ailia-models, pull requests merged in 2024-08, with the labels that each got.

#1406 Implement volo
  README.md
  image_classification/volo/LICENSE
  image_classification/volo/README.md
  image_classification/volo/pizza.jpg
  image_classification/volo/volo.py
  image_classification/volo/volo_labels.py
  scripts/download_all_models.sh
Labels: waiting_enhancement

#1398 Add DepthAnything
  README.md
  depth_estimation/depth_anything/LICENSE
  depth_estimation/depth_anything/README.md
  depth_estimation/depth_anything/demo1.png
  depth_estimation/depth_anything/depth_anything.py
  depth_estimation/depth_anything/depth_anything_util/transform.py
  depth_estimation/depth_anything/output.png
  scripts/download_all_models.sh
Labels: waiting_enhancement

#1353 Implement DRBN SKF
  README.md
  low_light_image_enhancement/drbn_skf/LICENSE
  low_light_image_enhancement/drbn_skf/README.md
  low_light_image_enhancement/drbn_skf/drbn_skf.py
  low_light_image_enhancement/drbn_skf/input.png
  low_light_image_enhancement/drbn_skf/output1.png
  low_light_image_enhancement/drbn_skf/output2.png
  scripts/download_all_models.sh
Labels: require_improve_ailia_sdk

#1075 Implement codeformer
  README.md
  face_restoration/codeformer/LICENSE
  face_restoration/codeformer/README.md
  face_restoration/codeformer/codeformer.py
  face_restoration/codeformer/codeformer_util.py
  face_restoration/codeformer/input.png
  face_restoration/codeformer/output.png
  scripts/download_all_models.sh
Labels: waiting_enhancement

#1248 Implement dtln
  README.md
  audio_processing/dtln/1221-135766-0000.wav
  audio_processing/dtln/LICENSE
  audio_processing/dtln/README.md
  audio_processing/dtln/dtln.py
  scripts/download_all_models.sh
Labels: require_improve_ailia_sdk

#1330 Latent consistency model txt2img
  README.md
  diffusion/latent-consistency-models/LICENSE.txt
  diffusion/latent-consistency-models/Output/0000.png
  diffusion/latent-consistency-models/README.md
  diffusion/latent-consistency-models/latent-consistency-models.py
  diffusion/latent-consistency-models/schedulerLCM.py
  diffusion/latent-consistency-models/tokenizer/merges.txt
  diffusion/latent-consistency-models/tokenizer/special_tokens_map.json
  diffusion/latent-consistency-models/tokenizer/tokenizer_config.json
  diffusion/latent-consistency-models/tokenizer/vocab.json
  scripts/download_all_models.sh
Labels: high priority
